#!/bin/sh

cp "$atlib"/initialise.cron "$at_build_dir"/initialise.cron
chmod 755 "$at_build_dir"/initialise.cron

cat <<EOF >"$at_meta_dir"/ks.post/initialiser-1.nochroot
#!/bin/sh
cp /mnt/source/initialise.cron /mnt/sysimage/root/initialise.cron
EOF

cat <<EOF >"$at_meta_dir"/ks.post/initialiser-2
#!/bin/sh
(
  crontab -l 2>/dev/null
  echo '* * * * *' /root/initialise.cron
) | crontab
EOF
