#!bash
# sourced within atwan
#
# Configure puppet as the new server's configuration management tool.
#
# Bootstrapping is handled by running puppet apply instead of puppet agent.
#
# The -E option is mandatory until I create something to act as its default.

if [[ -v at_optarg_b && -v at_optarg_P ]]; then
  echo Maybe in the future it will make sense to connect to a puppet master on >&2
  echo a bootstrapped note, but not now.  >&2
  echo 'The bootstrap (-b) and puppet master (-P) options are incompatible.' >&2
  return 1
fi

if [[ -v at_optarg_b ]]; then
  at_puppet_options="apply --verbose"

  if [[ -v at_optarg_C ]]; then
    at_puppet_options=$at_puppet_options\ $at_optarg_C
  fi

else
  at_puppet_options="agent --verbose"

  if [[ -v at_optarg_P ]]; then
    at_puppet_options="$at_puppet_options --server $at_optarg_P"
  fi
  if [[ -v at_optarg_T ]]; then
    at_puppet_options="$at_puppet_options --waitforcert $at_optarg_T"
  fi

  echo \ \ Puppet Master${at_optarg_P:+: $at_optarg_P}
fi

push at_variables at_puppet_options

push at_autorun_steps puppet_install puppet_start

### autostep_puppet_install must be defined by a release
cat >"$at_meta_dir"/puppet-start.autorun <<'EVERYTHING'
autostep_puppet_start() {
  if [ "$at_puppet_trust" = embedded ]; then
    for type in localcacert hostcert hostprivkey; do
      path=$(puppet agent --configprint $type)
      parent=$(dirname "$path")
      mkdir -p "$parent"
      cp -a "$at_top"/puppet.$type "$path"
      chown puppet:puppet "$path"
    done
  fi

  puppet $at_puppet_options
}
EVERYTHING

if [[ ! -v at_optarg_Z ]]; then
  unset at_continue
fi
