#!bash
# sourced within atwan
#
# If a bootstrap image is being built and the -E option is specified, create
# the tarball which will be used to bootstrap.

if [[ -v at_optarg_b ]]; then
  if [[ -v at_optarg_E ]]; then
    echo \ \ Yes.
  else
    echo \ \ Stand-alone configuration server.
  fi
else
  echo \ \ No.
  return
fi

if [[ ! -v at_optarg_E ]]; then
  echo There is no default tarball. >&2
  return 1

else
  if [[ -d $at_optarg_E ]]; then
    newtgz=$(mktemp ${at_work_dir:+--tmpdir="$at_work_dir"})
    tar czf "$newtgz" -C "$at_optarg_E" .
    mv "$newtgz" "$at_build_dir"/etc.tgz
  else
    cp "$at_optarg_E" "$at_build_dir"/etc.tgz
  fi
fi

push at_autorun_steps bootstrap

cat >"$at_meta_dir"/bootstrap.autorun <<'EVERYTHING'
# Extract the bootstrap tarball in /etc. Note that this will walk all over /etc
# without prejudice so make sure the tarball is safe.
#
autostep_bootstrap() {
  tar xz -C /etc <"$at_top"/etc.tgz
}
EVERYTHING
