#!bash
# sourced within atwan
#
# Create the initialisation package from the build dir as an ISO.

newimg=$(mktemp ${at_work_dir:+--tmpdir="$at_work_dir"})
echo Generating initialiser image in \""$newimg"\".
case "$at_optarg_F" in
  iso)
    xorriso -outdev "$newimg" -map "$at_build_dir" /
    ;;
  tgz)
    tar c -C "$at_build_dir" . | gzip -9c >"$newimg"
    ;;
esac
save_out_file "$newimg"
