#!bash
# sourced within atwan
#
# Set the new server's hardware clock, probably with ntpdate.

if [[ ! -v at_optarg_t ]]; then
  echo \ \ No.
  return 0
fi

echo '####' I am too lazy to write this bit. >&2
return 1
echo No.
