#!bash
# sourced within atwan
#
# Set the new server's hostname.

at_fqdn=$at_optarg_n
at_hostname=${at_optarg_n%%.*}
at_domain=${at_optarg_n#*.}
echo \ \ Hostname: $at_fqdn
push at_variables at_fqdn at_hostname at_domain
push at_autorun_steps hostname
