#!bash
# sourced within atwan
#
# Set up the components necessary to ensure logging works early.

if [[ ! -v at_optarg_l ]]; then
  echo \ \ No.
  return 0
fi

echo '####' I am too lazy to write this bit. >&2
return 1
