#!bash
# sourced within atwan
#
# Configure the system software sources (eg. apt or yum).

if [[ ! -v at_optarg_y ]]; then
  echo \ \ No.
  return 0
fi

echo '####' I am too lazy to write this bit. >&2
return 1
