#!bash
# sourced within atwan
#
# Stop the initialiser script from scanning for initialiser packages.
#
# This should be done first.

# autostep_stop_initialiser is included in the gold image's initialiser script
# when it is originally set up.
push at_autorun_steps stop_initialiser
