#!bash
# sourced within atwan
#
# Set the new server's custom variables.

# Atwan's default mode is to create a list variable containing the name of each
# variable which will be saved in the initialisation package. This file just
# prepares the list of variables to export (at_variables) which the build step
# is responsible for writing to the variables file.

unset at_variables
touch "$at_build_dir"/variables
