#!/bin/bash
. "$(dirname $0)"/atwan.installdirs

set -e

unset overwrite
outfile=/tmp/goldimage-setup.iso
if [ -e /etc/debian_version ]; then
  flavour=debian
elif [ -e /etc/centos-release ]; then
  flavour=centos
else
  unset flavour
fi
at_root_password=secret
#at_source_url=http://mirror.bytemark.co.uk/centos/6.4/isos/x86_64/CentOS-6.4-x86_64-minimal.iso
at_source_url=$HOME/Downloads/CentOS-6.4-x86_64-minimal.iso

usage() {
cat <<EOF
  Usage:
    mkiso-goldimage-iso [-O] [-o <output>] [-f <flavour>]
      [-p <root password>] -u <iso url>

  Options:
    -O: Overwrite old image if it exists.
    -o: Output filename.
        $outfile
    -f: Flavour (eg. Linux distribution) of gold image.
	See some place I haven't decided yet for a list of available flavours.

    -p: Gold Image root user's password.
	Default: $at_root_password
    -u: Installer image URL.
	$at_source_url
EOF
}

while getopts 'Oo:f:p:u:' arg; do
  case $arg in
    O) overwrite=1 ;;
    o) outfile=$OPTARG ;;
    f) flavour=$OPTARG ;;
    c) at_root_password=$OPTARG ;;
    u) at_source_url=$OPTARG ;;
    ?)
      usage
      exit 1
      ;;
  esac
done
shift $(expr $OPTIND - 1)

if ! [ -e "$atlib/flavour/$flavour" ]; then
  echo Unknown OS flavour: $flavour. >&2
  echo Check $atlib/flavour. >&2
  exit 1
fi

at_flib="$atlib/flavour/$flavour"
. "$at_flib/variables"

export atbin atlib at_flib at_source_url at_root_password
export at_build_dir=$(mktemp -d)
export at_meta_dir=$(mktemp -d)
trap 'chmod +rwX -R "$at_build_dir" "$at_meta_dir" && rm -fr "$at_build_dir" "$at_meta_dir"' EXIT

steps=(
  "prepare:     Preparing build directory."
  "extract:     Extracting $name image to $at_build_dir."
  "initialiser: Attaching initialiser script."
  "autoinstall: Setting up autoinstaller."
)

for step in "${steps[@]}"; do
  script=${step%%:*}
  message=${step#*:}
  if [ -e "$at_flib/$script" ]; then
    echo $message
    "$at_flib/$script"
  fi
done

echo Creating README.
cat <<EOF >"$at_build_dir"/README.atwan
This ISO is a remixed $name installer iso used to install and prepare it for
automatic configuration.

EOF

if [ -e "$at_flib/append-readme" ]; then
  echo Appending $name-specific information to README.
  "$at_flib/append-readme" >> "$at_build_dir"/README.atwan
fi

newfs=$(mktemp)
if [ -e "$at_flib/generate-iso" ]; then
  echo Generating output image in $newfs
  "$at_flib/generate-iso" "$newfs"
else
  echo "$at_flib/generate-iso does not exist. Don't know what to do." >&2
  exit 1
fi

if [ -e "$outfile" ]; then
  echo "$outfile is in the way." >&2
  if [ -z "$overwrite" ]; then
    echo "Leaving generated image as $newfs."
    exit 0
  fi

  echo "Deleting it as instructed."
  rm -f "$outfile"
fi
mv "$newfs" "$outfile"

echo Finished.
