#!bash
# sourced within atwan
#
# Configure salt minion as the new server's configuration management tool.

if [[ -v at_optarg_B && -v at_optarg_M ]]; then
  echo Maybe in the future it will make sense to connect to a salt master on >&2
  echo a bootstrapped note, but not now.  >&2
  echo 'The bootstrap (-B) and salt master (-M) options are incompatible.' >&2
  return 1
fi

if [[ -v at_optarg_B ]]; then
  at_salt_minion_command="salt-call"
  at_salt_minion_options="--local state.highstate"

  if [[ -v at_optarg_C ]]; then
    at_puppet_options="$at_salt_minion_options $at_optarg_C"
  fi

else
  at_salt_minion_command="salt-minion"

  if [[ -v at_optarg_M ]]; then
    at_salt_master_address=$at_optarg_M
    echo "  Salt master: $at_salt_master_address"
    at_variables+=(at_salt_master_address)
  fi
fi

at_variables+=(at_salt_minion_command at_salt_minion_options)

### autostep_salt_minion_install must be defined by a release
at_autorun_steps+=(salt_start)

if [[ ! -v at_optarg_P ]]; then
  echo WARNING: No salt master certificate fingerprint given. >&2
  if [[ ! -v at_optarg_W ]]; then
    echo "Not continuing without the pwn-me option (-W)." >&2
    return 1
  fi
  echo "Continuing anyway like a dummy." >&2
fi

if [[ -v at_optarg_P ]]; then
  at_salt_master_fingerprint=$at_optarg_P
  at_variables+=(at_salt_master_fingerprint)
fi

if [[ ! -v at_optarg_z ]]; then
  unset at_continue
fi

cat >"$at_meta_dir"/saltstack.autorun <<'EVERYTHING'
autostep_salt_start() {
  salt_install_package

  if [ x"$at_salt_master_address" != x ]; then
    echo "master: $at_salt_master_address" >> /etc/salt/minion
  fi

  if [ x"$at_salt_master_fingerprint" != x ]; then
    echo "master_finger: $at_salt_master_fingerprint" >> /etc/salt/minion
  fi

  "$at_salt_minion_command" $at_salt_minion_options
}
EVERYTHING

