#!bash
# sourced within atwan
#
# The puppet plugin's own trust model entails creating a new keypair using the
# puppet master (connected to with ssh if the -A option is given) and including
# the private part in the initialiser package.

if [[ -v at_optarg_b ]]; then
  echo \ \ Bootstrap trust is implicit.
  return 0
fi

if [[ ! -v at_optarg_P ]]; then
  echo WARNING: No salt master certificate fingerprint given. >&2
  if [[ ! -v at_optarg_D ]]; then
    echo "Not continuing without the dummy option (-D)." >&2
    return 1
  fi
  echo "Continuing anyway like a dummy." >&2
fi

if [[ -v at_optarg_P ]]; then
  at_salt_master_fingerprint=$at_optarg_P
  push at_variables at_salt_master_fingerprint
  push at_autorun_steps salt_minion_trust
fi

cat >"$at_meta_dir"/salt-minion-trust.autorun <<'EVERYTHING'
autostep_salt_minion_trust() {
  mkdir -p /etc/salt/minion.d
  echo "master_finger: $at_salt_master_fingerprint" > /etc/salt/minion.d/atwan-minion_trust.conf
}
EVERYTHING

if [[ ! -v at_optarg_z ]]; then
  unset at_continue
fi
