#!bash
# sourced within atwan
#
# Configure networking on the new server.

at_step_dir=$at_step_dir/.. source "$at_step_dir/../networking"

cat >"$at_meta_dir"/networking.autorun <<'EVERYTHING'
# Configure eth0.
autostep_net_ip4() {
  cat >/etc/sysconfig/network-scripts/ifcfg-eth0 <<-EOF
	DEVICE=eth0
	ONBOOT=yes
	TYPE=Ethernet
	BOOTPROTO=none
	IPADDR=$at_ip
	NETMASK=$at_mask
	GATEWAY=$at_gateway
EOF
}

# Configure DNS in /etc/resolv.conf
autostep_net_dns() {
  rm -f /etc/resolv.conf
  if [ -n "$at_dns_search" ]; then
    echo search $at_dns_search > /etc/resolv.conf
  fi
  for ns in $at_dns; do
    echo nameserver $ns
  done >> /etc/resolv.conf
}

# Configure a system-wide HTTP proxy.
autostep_net_proxy() {
  (
    echo http_proxy=\""$at_proxy"\"
    echo https_proxy=\""$at_proxy"\"
    echo ftp_proxy=\""$at_proxy"\"
  ) >> /etc/environment

  echo proxy="$at_proxy" >>/etc/yum.conf
}

# Bring up the network device
autostep_net_ifup() {
  ifup eth0
}
EVERYTHING
