#!bash
# sourced within atwan
#
# Configure networking on the new server.

# The Centos 6.4 plugin is exactly the same as Debian's and should be moved to
# the main plugin (TODO).

at_ip=$at_optarg_i
at_mask=$at_optarg_m
at_gateway=${at_optarg_g:-${at_ip%.*}.1}
echo \ \ IP: $at_ip
echo \ \ Netmask: $at_mask
echo \ \ Gateway: $at_gateway
push at_variables at_ip at_mask at_gateway
push at_autorun_steps net_ip4

at_dns=$at_optarg_d
push at_variables at_dns
echo \ \ DNS Servers: $at_dns
at_dns_search=${at_optarg_n#*.}
if [[ "$at_dns_search" ]]; then
  echo \ \ DNS Search: $at_dns_search
  push at_variables at_dns_search
fi
push at_autorun_steps net_dns

if [[ -v at_optarg_h ]]; then
  echo \ \ HTTP Proxy: $at_proxy
  at_proxy=$at_optarg_h
  push at_variables at_proxy
  push at_autorun_steps net_proxy
fi

push at_autorun_steps net_ifup
