#!bash
# sourced within atwan
#
# Use the global initialiser step script to include the initialiser script on
# the CD, then get it copied to /root and added to the system crontab on the
# newly installed gold image.

at_step_dir=$at_step_dir/.. source "$at_step_dir/../initialiser" # Copies cron script

cat <<EOF >"$at_meta_dir"/preseed.late/initialiser
cp /cdrom/initialiser-cron /target/root/atwan-initialiser;
echo '* * * * *' root /root/atwan-initialiser >/target/etc/cron.d/atwan-initialiser
EOF
