#!/bin/sh

if [ -e /etc/puppet ]; then
  echo /etc/puppet already exists. Moving it to /etc/puppet.atwan-backup >&2
  mv /etc/puppet /etc/puppet.atwan-backup
fi

tar xz -C /etc < "$at_top"/puppet.tgz
