#!/bin/sh
set -e

puppet_tmpdir=$(mktemp ${at_work_dir:+--tmpdir="$at_work_dir"} -d)
trap 'chmod +rw -R "$puppet_tmpdir"; rm -fr "$puppet_tmpdir"' EXIT
rsync -a "$at_puppet_dir"/ "$puppet_tmpdir"/puppet/
if [ "$at_bootstrap" = pm ]; then
  if [ -e "$puppet_tmpdir"/puppet/bootstrap-enc ]; then
    echo bootstrap-enc already exists in $at_puppet_dir. >&2
    echo Using it instead. >&2
  else
    cp "$at_lib"/mkinit-bootstrap-enc "$puppet_tmpdir"/puppet/bootstrap-enc
  fi
  chmod 755 "$puppet_tmpdir"/puppet/bootstrap-enc
fi

tar czf "$at_build_dir"/puppet.tgz -C "$puppet_tmpdir" puppet
cp "$at_lib"/autorun-bootstrap "$at_build_dir"/autorun-bootstrap
chmod 755 "$at_build_dir"/autorun-bootstrap
