#!bash
# sourced within atwan

at_step_dir=$at_step_dir/.. source "$at_step_dir/../hostname"

cat >"$at_meta_dir"/hostname.autorun <<'EVERYTHING'
# Configure the hostname in the appropriate locations and restart services to
# reflect the change live.
autostep_hostname() {
  sed "s/\\(127\\.0\\.1\\.1[[:space:]]\\+\\)localhost/\\1$at_fqdn $at_hostname/" -i /etc/hosts
  echo "$at_hostname" >/etc/hostname
  hostname "$at_hostname"
  pkill getty
  /etc/init.d/rsyslog restart
}
EVERYTHING
