#!bash
# sourced within atwan
#
# Set up apt.
#
# Hardware clock and entropy are not yet supported.

# If the argument to the -y option does not contain a space it is assumed to be
# just the URL and is transformed into a complete sources.list line before
# being included as the at_repo variable.

if [[ -v at_optarg_y ]]; then
  if [[ $at_optarg_y =~ ' ' ]]; then
    at_apt_repo=$at_optarg_y
    echo \ \ APT source entry: \""$at_repo"\"
  else
    at_apt_repo="deb $at_optarg_y $at_release_codename main"
    echo \ \ APT repository: $at_repo
  fi
  at_variables+=(at_apt_repo)
  at_autorun_steps+=(apt)
  unset at_optarg_y
fi

cat >"$at_meta_dir"/software.autorun <<'EVERYTHING'
# Configure a remote apt repository
autostep_apt() {
  echo "$at_apt_repo" > /etc/apt/sources.list

  apt-get update
}
EVERYTHING
