#!bash
# sourced within atwan
#
# Debian-specific code to configure networking on the new server.

at_step_dir=$at_step_dir/.. source "$at_step_dir/../networking"

cat >"$at_meta_dir"/networking.autorun <<'EVERYTHING'
# Configure the hostname in the appropriate locations and restart services to
# reflect the change live.
autostep_hostname() {
  sed "s/\\(127\\.0\\.1\\.1[[:space:]]\\+\\)localhost/\\1$at_fqdn $at_hostname/" -i /etc/hosts
  echo "$at_hostname" >/etc/hostname
  hostname "$at_hostname"
  pkill getty
  /etc/init.d/rsyslog restart
}

# Add an IPv4 stanza to /etc/network/interfaces
#
# IPv6 is not supported yet.
autostep_net_ip4() {
  cat >>/etc/network/interfaces <<-EOF
	auto eth0
	iface eth0 inet static
	  address $at_ip
	  netmask $at_mask
	  gateway $at_gateway
EOF
}

# Configure DNS in /etc/resolv.conf
autostep_net_dns() {
  rm -f /etc/resolv.conf
  if [ -n "$at_dns_search" ]; then
    echo search $at_dns_search > /etc/resolv.conf
  fi
  for ns in $at_dns; do
    echo nameserver $ns
  done >> /etc/resolv.conf
}

# Configure a system-wide HTTP proxy.
autostep_net_proxy() {
  (
    echo http_proxy=\""$at_proxy"\"
    echo https_proxy=\""$at_proxy"\"
    echo ftp_proxy=\""$at_proxy"\"
  ) >> /etc/environment

  (
    echo "Acquire::http { Proxy \"$at_proxy\"; };"
    echo "Acquire::ftp { Proxy \"$at_proxy\"; };"
  ) >> /etc/apt/apt.conf.d/proxy
}

# Bring up the network device
autostep_net_ifup() {
  ifup eth0
}
EVERYTHING
