#!/bin/sh

set -e

if [ "$at_source_url" != "${at_source_url#http}" ]; then
  dl="$(mktemp ${at_workdir:---tmpdir=$at_workdir})"
  trap "rm -f $dl" EXIT
  wget -O $dl "$at_source_url"
  at_source_url=$dl
fi

xorriso -indev "$at_source_url" -osirrox on -extract / "$at_build_dir"
