#!/bin/sh

set -e

cp "$at_lib"/initialiser-cron "$at_build_dir"/atwan-initialiser
chmod 755 "$at_build_dir"/atwan-initialiser

cat <<EOF >"$at_meta_dir"/ks.post/initialiser-1.nochroot
#!/bin/sh
cp /mnt/source/atwan-initialiser /mnt/sysimage/root/atwan-initialiser
EOF

cat <<EOF >"$at_meta_dir"/ks.post/initialiser-2
#!/bin/sh
(
  crontab -l 2>/dev/null
  echo '* * * * *' /root/atwan-initialiser
) | crontab
EOF
