#!/bin/sh

set -e

echo Installing kickstart to "$at_build_dir"/ks.cfg

"$at_lib_release"/autoinstall-kickstart.options   >"$at_build_dir"/ks.cfg
"$at_lib_release"/autoinstall-kickstart.packages >>"$at_build_dir"/ks.cfg

echo Appending kickstart pre and post script sections.

for section in pre post; do
  if [ $(ls -1 "$at_meta_dir"/ks.$section/ 2>/dev/null | wc -l) -ge 1 ]; then
    for file in "$at_meta_dir"/ks.$section/*; do
      if [ "$file" != "${file%.nochroot}" ]; then
	echo %$section --nochroot
      else
	echo %$section
      fi
      cat "$file"
      echo %end
    done
  fi
done >>"$at_build_dir"/ks.cfg

echo Updating isolinux.
chmod +w "$at_build_dir"/isolinux
sed '/label linux/{i label auto\
  menu label Install an automatic gold image (WIPES ALL DATA)\
  kernel vmlinuz\
  append initrd=initrd.img ks=cdrom:/ks.cfg
}' -i "$at_build_dir"/isolinux/isolinux.cfg 
chmod -w "$at_build_dir"/isolinux "$at_build_dir"/isolinux/isolinux.cfg
