#!bash
# sourced within atwan
#
# Include the command to install puppet in Debian.

at_step_dir=$at_step_dir/.. source "$at_step_dir/../configuration"

cat >"$at_meta_dir"/puppet-install.autorun <<'EVERYTHING'
autostep_puppet_install() {
  apt-get -y install puppet
}
EVERYTHING
