#!/bin/sh

set -e

echo Installing preseed to "$at_build_dir"/atwan.preseed

"$at_lib_release"/bootloader-preseed.options  >"$at_build_dir"/atwan.preseed
"$at_lib_release"/bootloader-preseed.partman >>"$at_build_dir"/atwan.preseed

for section in early late; do
  if [ $(ls -1 "$at_meta_dir"/preseed.$section/ 2>/dev/null | wc -l) -ge 1 ]; then
    unset string
    for file in "$at_meta_dir"/preseed.$section/*; do
      string="$string$(tr -d \\n < "$file");"
    done
    echo d-i preseed/${section}_command string "$string"
  fi
done >>"$at_build_dir"/atwan.preseed

echo Updating isolinux.
chmod +w "$at_build_dir"/isolinux
prepend=$(mktemp ${at_work_dir:+--tmpdir="$at_work_dir"})
# netcfg/choose_interface=eth0 hostname=x domain=x 

sed <"$at_build_dir"/isolinux/txt.cfg >"$prepend" \
'/\(menu \)\?default/d;
s/^label.*/label atwan/;
s/menu label.*/menu label Automatic gold image (WIPES ALL DATA)/;
s/append/& language=C country=US locale=C keymap=us hostname=localhost domain= file=\/cdrom\/atwan.preseed/;' 
sed "1r $prepend" -i "$at_build_dir"/isolinux/txt.cfg
rm -f "$prepend"
chmod -w "$at_build_dir"/isolinux "$at_build_dir"/isolinux/isolinux.cfg
