#!/bin/bash

set -e

source "$at_lib"/atwan.lib

echo Installing preseed to "$at_build_dir"/atwan.preseed

cp "$(find_file "bootloader-preseed")" "$at_build_dir"/atwan.preseed

# Well this is nasty.
# partman-base's postinst script runs partman, which it has installed into /bin
# Install a script in /sbin, which is before /bin in $PATH, which will be
# called instead of the real partman.
#  * The cd must have an entry in fstab and it must be /media/cdrom or the
#    installer can't continue.
#  * sfdisk needs -D or grub-probe can't detect ext2 on /boot.
#  * grub-installer/bootdev can't be (hd0) so must be set when the device is
#    known.
cp "$(find_file "bootloader-fakepartman")" "$at_meta_dir"/preseed.early/fakepartman

# But grub-installer/bootdev is not 'seen' if set by debconf-set and the
# question gets asked. Include this in the pressed file so that debconf marks
# it as seen.
echo d-i grub-installer/bootdev string foo >>"$at_build_dir"/atwan.preseed

for section in early late; do
  if [ $(ls -1 "$at_meta_dir"/preseed.$section/ 2>/dev/null | wc -l) -ge 1 ]; then
    unset string
    for file in "$at_meta_dir"/preseed.$section/*; do
      string="$string$(tr -d \\n < "$file");"
    done
    echo d-i preseed/${section}_command string "$string"
  fi
done >>"$at_build_dir"/atwan.preseed

echo Updating isolinux.
chmod +w "$at_build_dir"/isolinux
prepend=$(mktemp ${at_work_dir:+--tmpdir="$at_work_dir"})

sed <"$at_build_dir"/isolinux/txt.cfg >"$prepend" \
'/\(menu \)\?default/d;
s/^label.*/label atwan/;
s/menu label.*/menu label Automatic gold image (WIPES ALL DATA)/;
s/append/& language=C country=US locale=C keymap=us hostname=localhost domain= file=\/cdrom\/atwan.preseed/;' 
sed "1r $prepend" -i "$at_build_dir"/isolinux/txt.cfg
rm -f "$prepend"
chmod -w "$at_build_dir"/isolinux "$at_build_dir"/isolinux/isolinux.cfg
